spring:
  datasource:
    url: jdbc:sqlserver://172.20.10.5:1433;databaseName=SplashScreenDB;encrypt=false
    username: sa
    password: reallyStrongPwd123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update